### ISSUE TITLE
Pandas frame.append depreciation

### ISSUE THREAD

**Issue by w-k-jones** [climate-processes/tobac#101]
The pandas dataframe.append() method is being depreciated in future, and it is advised to replace it with pandas.concat. It's currently being used in feature detection:

https://github.com/climate-processes/tobac/blob/eeb574c47fceab370008b3767804ed037a269f79/tobac/feature_detection.py#L264

Is it worth changing this? Would concat have a performance overhead?

**Comment by freemansw1** [comment]
I think it is worth changing this, if for no other reason than to reduce the number of warnings I have to see every time I run `pytest`. I doubt there's a performance penalty associated, either.

**Comment by freemansw1** [comment]
Resolved with #110
