### ISSUE TITLE
how to use Tobac

### ISSUE THREAD

**Issue by kux2002** [climate-processes/tobac#3]
Hi,
 I installed the tobac according to the Document sucessfully, but I don't know how to run this program. Can you provide a  example command to run this process?
  thank you

**Comment by mheikenfeld** [comment]
Hi,
there are a few small example notebooks in the folder called "example" in the repository that you can use to get an idea of how you can use tobac. These will automatically download a small example dataset to play around with it. Are you familiar with Jupyter notebooks?
I will make sure I add that to the documentation and  we will work on extending the documentation for the project as soon as possible!
