### ISSUE TITLE
Update the mathod of importing watershed

### ISSUE THREAD

**Issue by zxdawn** [climate-processes/tobac#42]
https://github.com/climate-processes/tobac/blob/06b4d6d5314672765edc6e4914d93a393109ee7a/tobac/themes/tobac_v1/mask_segmentation.py#L207

`watershed` should be called by `from skimage.segmentation import watershed` for the new version of `skimage`.

Otherwise, we will get the warning:

```
/xin/miniconda3/envs/tobac2.0_dev/lib/python3.8/site-packages/skimage/morphology/_deprecated.py:5: skimage_deprecation: Function ``watershed`` is deprecated and will be removed in version 0.19. Use ``skimage.segmentation.watershed`` instead.
```

**Comment by w-k-jones** [comment]
Have fixed this in the latest commit to the v2.0-dev branch
