### ISSUE TITLE
area_histogram

### ISSUE THREAD

**Issue by huangynj** [climate-processes/tobac#50]
https://github.com/climate-processes/tobac/blob/730fa9affc0b6e7d3facf525faf73cc3a6406e74/tobac/analysis.py#L319

should be:

features=calculate_area(features,mask,method_area)

**Comment by bugsuse** [comment]
https://github.com/climate-processes/tobac/blob/50a99a8c7f6db54895d80ea0e83799eafa200c64/tobac/analysis/analysis.py#L659

see in v2.0-dev branch.

**Comment by freemansw1** [comment]
Yes, this looks like a bug to me in the `main` and `dev` branches. I'll put together a PR soon for the `dev` branch.

**Comment by freemansw1** [comment]
This has been resolved by #66 being merged. Not sure why GitHub didn't close this automatically.
