### ISSUE TITLE
Mistakes and modifications of feature_detection_multithreshold 

### ISSUE THREAD

**Issue by zxdawn** [climate-processes/tobac#6]
https://github.com/climate-processes/tobac/blob/3c8abdf86f26b7a77f1143e05ee4bd1adc2f48a4/tobac/feature_detection.py#L22
It should be `threshold`

**Comment by zxdawn** [comment]
https://github.com/climate-processes/tobac/blob/3c8abdf86f26b7a77f1143e05ee4bd1adc2f48a4/tobac/feature_detection.py#L70

It should be:
```
# if looking for maximum, set values below threshold to 0 and scale by data maximum:
```

**Comment by zxdawn** [comment]
https://github.com/climate-processes/tobac/blob/3c8abdf86f26b7a77f1143e05ee4bd1adc2f48a4/tobac/feature_detection.py#L85

Don't need to specify and flatten the array. `np.unique` works for 2D array.

```
values, count = np.unique(labels, return_counts=True) 
```

Example:
```
import numpy as np
a = np.array([[1, 0, 0], [1, 0, 0], [2, 3, 4]])
print (np.unique(a, return_counts=True))
```
Output:
```
(array([0, 1, 2, 3, 4]), array([4, 2, 1, 1, 1], dtype=int64))
```

**Comment by mheikenfeld** [comment]
Thanks for spotting the mistake in the comments. There is actually another one, as there is no scaling and the comment for the next line is wrong, too. Will fix those.

Thanks for the hint about the unneccesary flattenning of the array, will simpify that as you suggested!

**Comment by freemansw1** [comment]
I believe that this issue has been addressed based on my review of the code. If this is in error and this hasn't yet been resolved, let us know and I can re-open the ticket.
