### ISSUE TITLE
Switching from `master` to `main`

### ISSUE THREAD

**Issue by freemansw1** [climate-processes/tobac#61]
GitHub, GitLab, and a number of other providers are switching the naming convention of the main repository branch from `master` to `main` (e.g., [https://sfconservancy.org/news/2020/jun/23/gitbranchname/ ](https://sfconservancy.org/news/2020/jun/23/gitbranchname/ ), [https://github.com/github/renaming](https://github.com/github/renaming)). I think we should do the same, although it is not without some work. GitHub now allows us to rename branches from the web: https://github.com/github/renaming , but I'm not sure if this will break anything else. Thoughts, all?

**Comment by freemansw1** [comment]
I'm going to suggest that we discuss this at the next developer's meeting in a week or so and if there are no objections raised there, I'd like to move forward with this change.

**Comment by w-k-jones** [comment]
Sorry, meant to reply to this before. But to be fair I think this is something we should just go ahead with and notify devs, rather than requiring any discussion

**Comment by freemansw1** [comment]
I have now completed this transition. Thanks all!
