### ISSUE TITLE
Using IPython in jupyter

### ISSUE THREAD

**Issue by zxdawn** [climate-processes/tobac#7]
It's better to use `%matplotlib inline` instead of `%matplotlib noteboo`. Otherwise, may get this error:
```
javascript error: ipython is not defined
```

**Comment by mheikenfeld** [comment]
The main reason to use `%matplotlib notebook` was to allow for interaction with the plot e.g. by zooming. I have never run into the error you mention, sounds like a more general ipython/jupyter problem to me...
