### ISSUE TITLE
Recommended Python Style

### ISSUE THREAD

**Issue by fsenf** [climate-processes/tobac#72]
I think we should provide a recommendation, what type of python style is be used for future contributions. This info should be included into the file: https://github.com/climate-processes/tobac/blob/v2.0-dev/CONTRIBUTING.md

@JuliaKukulies: Did you use black (https://pypi.org/project/black/) in your latest updates?

**Comment by JuliaKukulies** [comment]
Yes, I used black @fsenf. Maybe the following three changes can be submitted together in one PR as they belong together?
1. formatting check as an automatic action for PRs, 2. formatting of the existing code in the same style and 3. recommendation of python style in the [contribution file]( https://github.com/climate-processes/tobac/blob/v2.0-dev/CONTRIBUTING.md)

**Comment by freemansw1** [comment]
I think that's a great idea and great path forward @JuliaKukulies . The question is: do we want to bring this into `v1.x` or leave it for `v2.0-dev`? I'm open to either, but perhaps it makes sense to go ahead and do it?

**Comment by JuliaKukulies** [comment]
Fabulous! I hope to have this fixed by next week!

**Comment by freemansw1** [comment]
Most of this has now been resolved by #78, but we still need to resolve #79 before we can close this issue.

**Comment by freemansw1** [comment]
Now that #79 is closed, I'm marking this issue as resolved.
