### ISSUE TITLE
Enable pre-commit hooks with black

### ISSUE THREAD

**Issue by mgrover1** [climate-processes/tobac#82]
In addition to running black at the Github actions level, it would be helpful to running it when a user for commits their changes to the repo.

Here is a link to [the pre-commit docs](https://pre-commit.com)

**Comment by w-k-jones** [comment]
Looks fairly straightforward, as black formatting is one of the given examples. I'll put together a PR for this after we merge #78

**Comment by freemansw1** [comment]
This has been resolved by #96
