### ISSUE TITLE
travis-ci Integration still present on PRs to main

### ISSUE THREAD

**Issue by freemansw1** [climate-processes/tobac#86]
On pull requests to `main`, such as #84, the Travis-CI integration is still attached despite its webhook being deleted from Settings.  @mgrover1 given your experience with GitHub, any ideas?

**Comment by mgrover1** [comment]
I believe the `.travis.yml` file needs to be removed (https://github.com/climate-processes/tobac/blob/main/.travis.yml)

**Comment by mheikenfeld** [comment]
Yes, if we're not using Travis CI anymore, that file can be removed entirely!

**Comment by freemansw1** [comment]
Thanks Max and Max, I've deleted this file and marked this as closed for now.
