### ISSUE TITLE
Speed up feature_detection_multithreshold

### ISSUE THREAD

**Issue by zxdawn** [climate-processes/tobac#9]
If the area is large, the `feature_detection_multithreshold` function is slow.

I'll test parts of it and check which one costs most. Maybe we can use **numba**, **Cython** or **multiprocessing** to speed it up.

**Comment by mheikenfeld** [comment]
Yes, there is probably quite some room in terms of optimising things there before even having to use the more complex things you mentionned, just by optimizing the procedures as they are. I'll have a look at some profiling of that part of the code as soon as I find some time for it, too!

**Comment by mheikenfeld** [comment]
I have finally managed to work through the multithreshold feature detection step and managed to speed it up a lot by more than an order or magnitude. I will clean things up and create a pull request for that over the next days!

**Comment by zxdawn** [comment]
@mheikenfeld Glad to hear it! I can help test when you finish that pull :smile:

**Comment by mheikenfeld** [comment]
I've created the pull request (#27) with the updated multithreshold feature detection

**Comment by zxdawn** [comment]
Long time no see ;) I should close this now as you have sped up a lot in that PR.
