### ISSUE TITLE
`plotting.py` forces matplotlib backend to `agg`

### ISSUE THREAD

**Issue by freemansw1** [climate-processes/tobac#95]
In `tobac/plotting.py`, we force the Matplotlib backend to `agg`:
https://github.com/climate-processes/tobac/blob/e2af8e0c6f7e78f936c42539660bcb2b20e290c6/tobac/plotting.py#L2

This is not really good practice, especially as it's imported by default when users run `import tobac`. It's funny, @w-k-jones @galexsky and I were just talking about this. I'll get on a PR to fix this shortly.

**Comment by w-k-jones** [comment]
Good spot. Does it cause any problems to plotting when this is removed?

**Comment by freemansw1** [comment]
Resolved with #100
